# Generated by Django 2.2.6 on 2019-12-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danusan', '0002_auto_20191211_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danusan',
            options={'ordering': ['datetime']},
        ),
    ]
