# Generated by Django 2.2.6 on 2019-12-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danusan', '0002_auto_20191213_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danusandetail',
            name='detail',
        ),
        migrations.DeleteModel(
            name='ReviewModel',
        ),
        migrations.DeleteModel(
            name='DanusanDetail',
        ),
    ]
