# Generated by Django 2.2.7 on 2019-12-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danusan', '0003_auto_20191213_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danusan',
            name='slug',
        ),
    ]
