# Generated by Django 2.2.7 on 2019-12-13 15:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('danusan', '0004_remove_danusan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='danusan',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
