# Generated by Django 2.2.7 on 2019-12-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailDanusan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danusandetail',
            name='detail',
        ),
    ]
