# Generated by Django 2.2.7 on 2019-12-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danusan', '0004_remove_danusan_slug'),
        ('detailDanusan', '0002_remove_danusandetail_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='danusandetail',
            name='detail',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='danusan.Danusan'),
        ),
    ]
