# Generated by Django 2.2.7 on 2019-12-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danusan', '0005_danusan_slug'),
        ('detailDanusan', '0003_danusandetail_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='detail',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='danusan.Danusan'),
        ),
        migrations.DeleteModel(
            name='DanusanDetail',
        ),
    ]
